#!/usr/bin/env python3
"""
Alter the code from wait_n and into a new function task_wait_n:.
"""

import asyncio
from typing import List

task_wait_random = __import__('3-tasks').task_wait_random


async def task_wait_n(n: int, max_delay: int) -> List[float]:
    """
    Executes task_wait_random n times concurrently.

    Args:
        n (int): Number of times to execute task_wait_random.
        max_delay (int): Maximum delay parameter for task_wait_random.

    Returns:
        List[float]: List of random delays generated by task_wait_random.
    """
    wait_times = await asyncio.gather(
        *tuple(map(lambda _: task_wait_random(max_delay), range(n)))
    )
    return sorted(wait_times)
